// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/forbid-one-comment": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "封禁某条评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "commentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "ban",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/forbid-post": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "修改帖子权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "banOption",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "isAdd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/forbid-user": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "修改用户权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "userId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "banOption",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "isAdd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/modify-permission": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "修改网站权限配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "safeBan",
                        "name": "option",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "ban",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/modify-restriction": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "修改网站限制配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "maxDocumentHeight",
                        "name": "option",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "6000",
                        "name": "maxLimit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/view-permission": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "浏览网站权限配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/view-restriction": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "管理员方法"
                ],
                "summary": "浏览网站限制配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/adopt-help": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "采纳帮助者的帖子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "seekHelpId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "2",
                        "name": "lendHandId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/before-edit": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "编辑操作前的预判断",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "0",
                        "name": "postType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "seekHelpId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "2",
                        "name": "lendHandId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collect-post-list": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "请求收藏帖子列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "listType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/download-file": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "下载指定路径的文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filePath",
                        "name": "filePath",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/find-password": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "找回密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "loginType",
                        "name": "loginType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nameOrMail",
                        "name": "nameOrMail",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authCode",
                        "name": "authCode",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout-post-list": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "请求公共帖子列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "listType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "All",
                        "name": "language",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "sortOption",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mark-all-info": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "将所以消息标记为已读",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mark-single-info": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "将一条消息标记为已读",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/message-list": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "消息列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modify/comment": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "修改评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Hello",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2024-05-26 15:10:00",
                        "name": "updateTime",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/private-post-list": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "请求私人帖子列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "listType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/publish/comment": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "添加新的评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Hello",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2024-05-26 15:10:00",
                        "name": "sendTime",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "注册新用户，第一个注册的用户是管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "registerTime",
                        "name": "registerTime",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/send-code": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "发送验证码(一个验证码只能处理一个操作，用完就要删除)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update-collect": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "修改用户收藏夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "isAdd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upvote": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "给某个帖子(求助或者帮助)点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "false",
                        "name": "isAdd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/view/comment": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "浏览帖子所对应的评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/view/seek-help": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "浏览求助帖子，但其实修改一下swagger的Router，也可以浏览帮助帖子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "1",
                        "name": "postId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":\"0\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
